keywords = [
    "Revenue",
    "Earnings",
    "Earnings per Share",
    "EPS",
    "Net Asset Value",
    "NAV",
    "Share Repurchase",
    "Buyback",
    "Share count",
    "Capital Return",
    "Dividends",
    "Preferred Dividends",
    "Net Interest Income",
    "Earning Asset Yields",
    "Deposit Beta",
    "Non-interest Bearing Deposits",
    "Fed Funds",
    "Yield Curve steep",
    "flat",
    "inverted",
    "2 year – 10 year spread",
    "Economy",
    "Fee Income",
    "Mortgage Fees",
    "Investment Banking Fees",
    "Advisory Fees",
    "Market Fees",
    "Trading",
    "FICC",
    "Equity",
    "Alternative Investments",
    "Private Equity",
    "Private Credit",
    "Bond Issuance",
    "Purchase Volume",
    "Exchange Volume",
    "Trading Volume",
    "Transaction Margin",
    "Expenses",
    "Compensation Ratio",
    "Comp Ratio",
    "Efficiency Ratio",
    "Rate per contract",
    "Gross Purchase Volume",
    "Credit cost",
    "Net Charge Off",
    "Delinquency",
    "Subscription Revenues",
    "Recurring Revenues",
    "Wealth Management",
    "Pre-tax margins",
    "Operating margins",
    "Regulation",
    "Capital Requirements",
    "Common Equity Tier 1 Capital",
    "Leverage Ratio",
    "Tier 1 Leverage Ratio",
    "Risk-weighted assets",
    "Risk-weightings",
    "Occupancy",
    "Vacancy",
    "Loan-to-Value",
    "LTV",
    "Interest coverage",
    "Defaults",
    "Criticized Loan",
    "Commercial Real Estate",
    "Commercial and Industrial Loans",
    "C&I",
    "Unsecured lending",
    "Collateral value",
    "Net Interest Margin",
    "NIM",
    "Loan growth",
    "Jaws",
    "Cost/income ratio",
    "Basel III",
    "Bank taxes",
    "Provisions",
    "Non-performing loans",
    "Banking Union",
    "Cross border M&A",
    "ECB interest rate",
    "Minimum Reserve Requirement",
    "Political pressure",
    "AML litigation",
    "Macro overlay",
    "Asset quality",
    "Stage 2 loans",
    "Stage 3 loans",
    "Peak regulation",
    "Deposit fund contributions",
    "CDS spreads",
    "AT1",
    "Sovereign bond spreads",
    "Green financing",
    "Claims inflation",
    "Natural catastrophes",
    "nat cats",
    "Hard market",
    "Pricing",
    "Reserves",
    "Solvency",
    "IFRS17",
    "CSM",
    "Investments",
    "Capital buffer",
    "Premium growth",
    "Reinsurance",
    "Terms and conditions",
    "Exposure limits",
    "Renewals",
    "January",
    "April",
    "June",
    "Social inflation",
    "Litigation",
    "Hurricanes",
    "Used cars prices",
    "Climate risk",
    "Price",
    "Volume",
    "Gross margin",
    "Raw material",
    "Inflation",
    "Market share",
    "Regulation",
    "Rate case",
    "Interest rates",
    "Weather",
    "Power price",
    "Discounts",
    "Promotional activities",
    "Employee attrition",
    "Inflation",
    "Churn",
    "Seasonal products",
    "Inventory",
    "Logistics expense",
    "Fuel cost",
    "Wage increase",
    "Minimum wage",
    "Price increases",
    "Supplier price increase",
    "Raising guidance",
    "Sales drivers",
    "Margin improvement",
    "Revenue Growth Acceleration",
    "Revenue Growth Deceleration",
    "Generative AI",
    "Artificial Intelligence",
    "Product Cycle",
    "Upcoming Product Cycle",
    "Margin Expansion",
    "Buyback",
    "Share buyback",
    "Improved Competitive Environment",
    "Shrink",
    "Markdowns",
    "Markons",
    "Traffic",
    "Customer counts",
    "Average ticket",
    "Average basket",
    "UPT",
    "Units per transaction",
    "AUR",
    "Average unit retail",
    "Distribution costs",
    "Buying costs",
    "Rent",
    "Occupancy",
    "Wages",
    "Credit card fees",
    "Credit income",
    "Delinquencies",
    "Credit portfolio performance",
    "Incentive comp",
    "Repairs and maintenance",
    "Insurance",
    "Medical",
    "EBIT Margins",
    "Sales leverage",
    "Comps",
    "Same Store sales",
    "Seasonality",
    "Weather",
    "Out of stocks",
    "In stocks",
    "Lean",
    "Consumables",
    "Discretionary goods",
    "Sales acceleration",
    "Lean inventories",
    "New store productivity",
    "Trade down",
    "Trade up",
    "Private label",
    "Commodity pressure",
    "Higher gas prices",
    "SNAP",
    "Inventory/inventories",
    "Destocking",
    "Recovery",
    "Organic growth",
    "Utilization",
    "Cost trend",
    "Biologics",
    "Bioprocessing",
    "GLP-1/Ozempic",
    "Large molecule",
    "Penetration/penetrated",
    "Under-served",
    "Value-based care",
    "Risk adjustment",
    "Reimbursement",
    "Market share",
    "Procedures/volume",
    "Book-to-bill",
    "Contribution margin",
    "LIFO liquidation",
    "Orders",
    "Cancellation",
    "Restructuring",
    "Inventory destocking",
    "Backlogs",
    "Order rates",
    "Incremental margins",
    "Core growth",
    "Recurring revenue",
    "Aftermarket growth",
    "Materials inflation",
    "Price cost spread",
    "Labor shortage",
    "Supply chain bottlenecks",
    "Lead times",
    "Capacity utilization",
    "Electronic components",
    "Sustainability",
    "Infrastructure stimulus",
    "Renewables",
    "Decarbonization",
    "Hydrogen",
    "Megaprojects",
    "Electrification",
    "Digitization",
    "Automation",
    "Robotics",
    "Reshoring",
    "Nearshoring",
    "Regulation",
    "Intramodal",
    "Capex"
]
